export enum PermissionSubject {
  ALL = 'ALL',
  Supplier = 'Supplier',
  Role = 'Role',
  Transaction = 'Transaction',
  User = 'User',
  EmailTemplate = 'Email Template',
  CustomFields = 'Custom Fields',
  Restaurant = 'Restaurant',
  Table = 'Table',
  MenuCategory = 'Menu Category',
  MenuAddition = 'Menu Addition',
  MenuItem = 'Menu Item',
  KitchenQueue = 'Kitchen Queue',
  QrCode = 'Qr Code',
  Cashier = 'Cashier',
  ClientComment = 'Client Comment',
  ClientFeedback = 'Client Feedback',
  PaymentSetup = 'Payment Setup',
  List = 'List',
  Activity = 'Activity',
}
export enum CommonPermissions {
  LIST = 'LIST',
  FETCH = 'FETCH',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  MANAGE = 'MANAGE',
}
