export enum PermissionSubject {
  ALL = 'ALL',
  Supplier = 'Supplier',
  LedgerAccount = 'Ledger Account',
  LedgerAccountType = 'Ledger Account Type',
  Amenities = 'Amenities',
  Categories = 'Categories',
  SubCategories = 'Sub Categories',
  MarketingFee = 'Marketing Fee',
  MasterService = 'Master Service',
  Role = 'Role',
  Transaction = 'Transaction',
  User = 'User',
  Addon = 'Addon',
  Guest = 'Guest',
  List = 'List',
  Maintenance = 'Maintenance',
  Policy = 'Policy',
  Property = 'Property',
  RoomType = 'Room Type',
  Rate = 'Rate',
  SeasonalRate = 'Seasonal Rate',
  DerivedRate = 'Derived Rate',
  RentalUnit = 'Rental Units',
  TaxConfig = 'Tax Config',
  TaskType = 'Task Type',
  Task = 'Task',
  Reservation = 'Reservation',
  Folio = 'Folio',
  EmailTemplate = 'Email Template',
  CustomFields = 'Custom Fields',
  PropertyServicesRequest = 'Property Services Request',
  Invoice = 'Invoice',
}
export enum CommonPermissions {
  LIST = 'LIST',
  FETCH = 'FETCH',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  MANAGE = 'MANAGE',
}
export enum GuestPermission {
  AddNote = 'Add Note',
  RemoveNote = 'Remove Note',
  AddID = 'Add ID',
  RemoveID = 'Remove ID',
}
export enum ReservationPermission {
  AddMarketingInfo = 'Add Marketing Info',
  RemoveMarketingInfo = 'Remove Marketing Info',
  RoomAssignment = 'Room Assignment',
  ChangeStay = 'Change Stay',
  ArrivalDepartureTimeChange = 'Arrival Departure Time Change',
  CheckIn = 'Check In',
  CheckOut = 'Check Out',
  Cancel = 'Cancel',
  NoShow = 'No Show',
  Rollback = 'Rollback',
  Preview = 'Preview',
  Book = 'Book',
  FetchAvailability = 'Fetch Availability',
  AddAddon = 'Add Addon',
  RemoveAddon = 'Remove Addon',
  AddSpnService = 'Add Spn Service',
  RemoveSpnService = 'Remove Spn Service',
  UpdateDocuments = 'Update Documents',
  AddGuest = 'Add Guest',
  RemoveGuest = 'Remove Guest',
  AddNote = 'Add Note',
  RemoveNote = 'Remove Note',
  AddVehicle = 'Add Vehicle',
  RemoveVehicle = 'Remove Vehicle',
  Activities = 'Activities',
  CalculateTax = 'Calculate Tax',
}

export enum PropertyServiceRequestPermissions {
  UpdatePropertySupplierService = 'Update Property Supplier Service',
}
